import pymysql

conn = pymysql.connect(host='127.0.0.1', user='root', password='1234', db='menuDB', charset='utf8')
cur = conn.cursor()

cur.execute("INSERT INTO menuTable VALUES('불고기버거',1)")
cur.execute("INSERT INTO menuTable VALUES('새우버거',2)")
cur.execute("INSERT INTO menuTable VALUES('치킨버거',3)")
cur.execute("INSERT INTO menuTable VALUES('치즈버거',4)")
cur.execute("INSERT INTO menuTable VALUES('통새우와퍼',5)")
cur.execute("INSERT INTO menuTable VALUES('롱치킨버거',6)")
cur.execute("INSERT INTO menuTable VALUES('갈릭불고기와퍼',7)")
cur.execute("INSERT INTO menuTable VALUES('할라피뇨와퍼',8)")
cur.execute("INSERT INTO menuTable VALUES('치즈와퍼',9)")
cur.execute("INSERT INTO menuTable VALUES('불고기와퍼',10)")
cur.execute("INSERT INTO menuTable VALUES('와퍼',11)")
cur.execute("INSERT INTO menuTable VALUES('비엘티오믈렛킹모닝',12)")
cur.execute("INSERT INTO menuTable VALUES('오믈렛킹모닝',13)")
cur.execute("INSERT INTO menuTable VALUES('블랙어니언와퍼',14)")
cur.execute("INSERT INTO menuTable VALUES('블랙어니언치킨와퍼',15)")
cur.execute("INSERT INTO menuTable VALUES('블랙어니언엑스',16)")
cur.execute("INSERT INTO menuTable VALUES('골든치즈렐라엑스',17)")
cur.execute("INSERT INTO menuTable VALUES('골든치즈렐라와퍼',18)")
cur.execute("INSERT INTO menuTable VALUES('골든치즈렐라치킨버거',19)")
cur.execute("INSERT INTO menuTable VALUES('기네스콰트로치즈와퍼',20)")
cur.execute("INSERT INTO menuTable VALUES('기네스와퍼',21)")
cur.execute("INSERT INTO menuTable VALUES('몬스터와퍼',22)")
cur.execute("INSERT INTO menuTable VALUES('몬스터엑스',23)")
cur.execute("INSERT INTO menuTable VALUES('스태커투와퍼',24)")
cur.execute("INSERT INTO menuTable VALUES('스태커쓰리와퍼',25)")
cur.execute("INSERT INTO menuTable VALUES('불고기버거세트',26)")
cur.execute("INSERT INTO menuTable VALUES('새우버거세트',27)")
cur.execute("INSERT INTO menuTable VALUES('치킨버거세트',28)")
cur.execute("INSERT INTO menuTable VALUES('치즈버거세트',29)")
cur.execute("INSERT INTO menuTable VALUES('통새우와퍼세트',30)")
cur.execute("INSERT INTO menuTable VALUES('롱치킨버거세트',31)")
cur.execute("INSERT INTO menuTable VALUES('갈릭불고기와퍼세트',32)")
cur.execute("INSERT INTO menuTable VALUES('할라피뇨와퍼세트',33)")
cur.execute("INSERT INTO menuTable VALUES('치즈와퍼세트',34)")
cur.execute("INSERT INTO menuTable VALUES('불고기와퍼세트',35)")
cur.execute("INSERT INTO menuTable VALUES('와퍼세트',36)")
cur.execute("INSERT INTO menuTable VALUES('비엘티오믈렛킹모닝세트',37)")
cur.execute("INSERT INTO menuTable VALUES('오믈렛킹모닝세트',38)")
cur.execute("INSERT INTO menuTable VALUES('블랙어니언와퍼세트',39)")
cur.execute("INSERT INTO menuTable VALUES('블랙어니언치킨와퍼세트',40)")
cur.execute("INSERT INTO menuTable VALUES('블랙어니언엑스세트',41)")
cur.execute("INSERT INTO menuTable VALUES('골든치즈렐라엑스세트',42)")
cur.execute("INSERT INTO menuTable VALUES('골든치즈렐라와퍼세트',43)")
cur.execute("INSERT INTO menuTable VALUES('골든치즈렐라치킨버거세트',44)")
cur.execute("INSERT INTO menuTable VALUES('기네스콰트로치즈와퍼세트',45)")
cur.execute("INSERT INTO menuTable VALUES('기네스와퍼세트',46)")
cur.execute("INSERT INTO menuTable VALUES('몬스터와퍼세트',47)")
cur.execute("INSERT INTO menuTable VALUES('몬스터엑스세트',48)")
cur.execute("INSERT INTO menuTable VALUES('스태커투와퍼세트',49)")
cur.execute("INSERT INTO menuTable VALUES('스태커쓰리와퍼세트',50)")
cur.execute("INSERT INTO menuTable VALUES('너겟킹',51)")
cur.execute("INSERT INTO menuTable VALUES('치즈스틱',52)")
cur.execute("INSERT INTO menuTable VALUES('어니언링',53)")
cur.execute("INSERT INTO menuTable VALUES('감자튀김',54)")
cur.execute("INSERT INTO menuTable VALUES('콘샐러드',55)")
cur.execute("INSERT INTO menuTable VALUES('시즈닝',56)")
cur.execute("INSERT INTO menuTable VALUES('선데',57)")
cur.execute("INSERT INTO menuTable VALUES('아메리카노',58)")
cur.execute("INSERT INTO menuTable VALUES('핫초코',59)")
cur.execute("INSERT INTO menuTable VALUES('아이스초코',60)")
cur.execute("INSERT INTO menuTable VALUES('컵아이스크림',61)")
cur.execute("INSERT INTO menuTable VALUES('코카콜라',62)")
cur.execute("INSERT INTO menuTable VALUES('코카콜라제로',63)")
cur.execute("INSERT INTO menuTable VALUES('스프라이트',64)")
cur.execute("INSERT INTO menuTable VALUES('씨그램',65)")
cur.execute("INSERT INTO menuTable VALUES('미닛메이드오렌지',66)")
cur.execute("INSERT INTO menuTable VALUES('리얼독퍼',67)")
cur.execute("INSERT INTO numTable VALUES('하나',1)")
cur.execute("INSERT INTO numTable VALUES('한개',1)")
cur.execute("INSERT INTO numTable VALUES('둘',2)")
cur.execute("INSERT INTO numTable VALUES('두개',2)")
cur.execute("INSERT INTO numTable VALUES('셋',3)")
cur.execute("INSERT INTO numTable VALUES('세개',3)")
cur.execute("INSERT INTO numTable VALUES('넷',4)")
cur.execute("INSERT INTO numTable VALUES('네개',4)")
cur.execute("INSERT INTO numTable VALUES('다섯개',5)")




conn.commit()

conn.close()